// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"be-test/controllers"
	"be-test/repositories"
	"be-test/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func AppController() *controllers.ControllerRegistry {
	userRepositoryImpl := repositories.NewUserRepository()
	userServiceImpl := services.NewUserServiceImpl(userRepositoryImpl)
	redirectControllerImpl := controllers.NewRedirectController(userServiceImpl)
	controllerRegistry := controllers.NewControllerRegistry(redirectControllerImpl)
	return controllerRegistry
}

// wire.go:

var serviceSet = wire.NewSet(services.NewUserServiceImpl, wire.Bind(
	new(services.UserService),
	new(*services.UserServiceImpl),
),
)

var controllerSet = wire.NewSet(controllers.NewRedirectController, wire.Bind(
	new(controllers.RedirectController),
	new(*controllers.RedirectControllerImpl),
),
)

var repositorySet = wire.NewSet(repositories.NewUserRepository, wire.Bind(
	new(repositories.UserRepository),
	new(*repositories.UserRepositoryImpl),
),
)
