-- Create "credentials" table
CREATE TABLE "public"."credentials" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "password" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Modify "users" table
ALTER TABLE "public"."users" ADD COLUMN "credential_user" bigint NULL, ADD CONSTRAINT "users_credentials_user" FOREIGN KEY ("credential_user") REFERENCES "public"."credentials" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create index "users_credential_user_key" to table: "users"
CREATE UNIQUE INDEX "users_credential_user_key" ON "public"."users" ("credential_user");
